### ISSUE TITLE
Minify JS

### ISSUE THREAD

**Issue by gregbia** [JimSchofield/Guty-Blocks-2#1]
Is it possbile to add JS minification to the webpack? I tried the following:

```
....

const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = [
    // Config for regular blocks
    {

      ....

      optimization: {
	 minimizer: [
	   new UglifyJsPlugin()
	 ]
      },

....
```

It does not cause any errors on build but the code build.js is not minified.

**Comment by JimSchofield** [comment]
In a recent update I added `npm run build:prod` which will minify the gutenberg block js files.
